In [ ]:
x = [i for i in range(15)] 
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [ ]:
a = [4,6,7,3,2]
b = [x*2 for x in a if x > 5]
print(b)

[12, 14]

In [ ]:
my_list = [2, 5, 8, 11, 15]
new_list = [x*2 if x < 10 else x+1 for x in my_list]
print(new_list)

[4, 10, 16, 12, 16]

In [ ]:
my_list = [i for i in range(1, 30) if i%2==0 if i%5==0]
print(my_list)

[10, 20]

In [ ]:
names = ['Ch','Dh','Eh','cb','Tb','Td']
new_names = [name for name in names if name.lower().startswith('c')]
print(new_names)

['Ch', 'cb']

In [ ]:
new_list = [num * 2 for num in range(5)]
print(new_list)

[0, 2, 4, 6, 8]

In [ ]:
new_list = [num for num in range(50) if  num > 20 and num % 2 == 0]
print(new_list)

[22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]

In [ ]:
fave_language_chars = [letter for letter in "Python"]
print(fave_language_chars)

['P', 'y', 't', 'h', 'o', 'n']

In [ ]:
'''
Find all of the numbers from 1-1000 that are divisible by 7

'''
new_list=[num for num in range(1 ,1001) if num % 7 ==0]
print(new_list)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]

In [ ]:
'''
Find all of the numbers from 1-1000 that have a 3 in them
'''
new_list=[num for num in range(1,1001) if '3' in str(num)]
print(new_list)

[3, 13, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 53, 63, 73, 83, 93, 103, 113, 123, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 143, 153, 163, 173, 183, 193, 203, 213, 223, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 243, 253, 263, 273, 283, 293, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 403, 413, 423, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 443, 453, 463, 473, 483, 493, 503, 513, 523, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 543, 553, 563, 573, 583, 593, 603, 613, 623, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 643, 653, 663, 673, 683, 693, 703, 713, 723, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 743, 753, 763, 773, 783, 793, 803, 813, 823, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 843, 853, 863, 873, 883, 893, 903, 913, 923, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 943, 953, 963, 973, 983, 993]

In [ ]:
'''
Count the number of spaces in a string
'''
some_string = 'the slow solid squid swam sumptuously through the slimy swamp'
string_list=[num for num in some_string if ' ' in  some_string]
print(len(string_list))

61

In [ ]:
'''
Create a list of all the consonants in the string "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
'''
sentence = "Yellow Yaks like yelling and yawning and yesturday they yodled while eating yuky yams"
vowel=['a' 'e' 'i' 'o' 'u']
consonants=[ch for ch in sentence if ch.lower() not in vowel]
print(consonants)

['Y', 'e', 'l', 'l', 'o', 'w', ' ', 'Y', 'a', 'k', 's', ' ', 'l', 'i', 'k', 'e', ' ', 'y', 'e', 'l', 'l', 'i', 'n', 'g', ' ', 'a', 'n', 'd', ' ', 'y', 'a', 'w', 'n', 'i', 'n', 'g', ' ', 'a', 'n', 'd', ' ', 'y', 'e', 's', 't', 'u', 'r', 'd', 'a', 'y', ' ', 't', 'h', 'e', 'y', ' ', 'y', 'o', 'd', 'l', 'e', 'd', ' ', 'w', 'h', 'i', 'l', 'e', ' ', 'e', 'a', 't', 'i', 'n', 'g', ' ', 'y', 'u', 'k', 'y', ' ', 'y', 'a', 'm', 's']

In [ ]:
'''
 Get the index and the value as a tuple for items in the list ["hi", 4, 8.99, 'apple', ('t,b','n')].  Result would look like [(index, value), (index, value)]
 '''

 vowel = [ 'a', 'e', 'i', 'o', 'u']
 r=[ (i,j) for i, j in enumerate(vowel)]
 print(r)

IndentationError: ignored

In [ ]:
'''
Find the common numbers in two lists (without using a tuple or set) list_a = [1, 2, 3, 4], list_b = [2, 3, 4, 5]
'''
list_a=[1,2,3,4]
list_b=[2,3,4,5]
common=[ch for ch in list_a if ch in list_b]
print(common)

[2, 3, 4]

In [ ]:
'''
Get only the numbers in a sentence like 'In 1984 there were 13 instances of a protest with over 1000 people attending'.  Result is a list of numbers like [3,4,5]
'''
sentence = 'In 1984 there were 13 instances of a protest with over 1000 people attending'
sen = sentence split()
num = [ch for ch in ]

SyntaxError: ignored

In [ ]:
'''
Produce a list of tuples consisting of only the matching numbers in these lists list_a = [1, 2, 3,4,5,6,7,8,9], list_b = [2, 7, 1, 12].  Result would look like (4,4), (12,12)
'''

In [ ]:
'''Find all of the words in a string that are less than 4 letters'''
sentence = 'On a summer day somner smith went simming in the sun and his red skin stung'